project_id = "wbfxpvncphdkxmxipmth"
 
 [functions.travel-assistant]
 verify_jwt = false

[functions.signup-with-validation]
verify_jwt = false

[functions.ai-trip-planner]
verify_jwt = false

[functions.admin-notification]
verify_jwt = false
